### ISSUE TITLE
train my own dataset and run the test , get all of the results : ap=-1, but i don't know why

### ISSUE THREAD

**Issue by lyumazi** [xingyizhou/CenterNet#415] opened 2019-10-22 06:18 UTC
![图片](https://user-images.githubusercontent.com/37330860/67262391-34a6bf80-f4d7-11e9-8c3d-ada32d3308b8.png)
i compared the  results of one image with my annotation file.
it looks ok exclude the undetected。
but my test also return the ap=-1 in all conditions.
![图片](https://user-images.githubusercontent.com/37330860/67262192-72571880-f4d6-11e9-80aa-87c5c010f0c4.png)
i have check the input of the cocoeval function, there is noting wrong .
so i have no idea about the problem. who can help me.
i have been solvoing this for 3 days……

**Comment by lyumazi** [comment] 2019-10-23 11:15
because my val file lost some important content，the categories part is null. so the cocoeval can't get all the useful info to calculate
i am so stupid 555

**Comment by xingyizhou** [comment] 2019-10-30 02:57
It seems the issue is solved. Closing it for now.

**Closed by xingyizhou** 2019-10-30 02:57 UTC

**Comment by lyumazi** [comment] 2019-12-25 12:27
yep, I have solved it .thx so much for your reply! i am so sorry to check the email so late.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xingyi Zhou"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 上午10:57
收件人: "xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;; 
抄送: "550797050"<550797050@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xingyizhou/CenterNet] train my own dataset and run the test , get all of the results : ap=-1, but i don&#39;t know why (#415)




It seems the issue is solved. Closing it for now.

**Comment by ujsyehao** [comment] 2020-02-23 04:11
＠lyumazi, Can you post your val.json？
