### ISSUE TITLE
A problem about parameter"opt.num_stacks"

### ISSUE THREAD

**Issue by ZhWL123456** [xingyizhou/CenterNet#430] opened 2019-10-25 13:50 UTC
In the ./src/bin/opts.py file, the opt.num_stacks =2 if opt.arch =='hourglass' else 1.
If there anybody know why it was defined like this？ What's the meaning of the parameter?
Thank u!

**Comment by xingyizhou** [comment] 2019-10-26 19:21
The hourglass network has intermediate supervision as the first stack. Please check the stacked hourglass net paper for the specific design.

**Comment by ZhWL123456** [comment] 2019-10-28 07:06
> The hourglass network has intermediate supervision as the first stack. Please check the stacked hourglass net paper for the specific design.
Thank u~ After read it, I got some thoughts！😊

**Comment by ZhWL123456** [comment] 2019-10-28 07:07
> The hourglass network has intermediate supervision as the first stack. Please check the stacked hourglass net paper for the specific design.
Thank u~ After read it, I got some thoughts！😊

**Comment by xingyizhou** [comment] 2019-10-30 02:57
It seems the issue is resolved. Closing it for now.

**Closed by xingyizhou** 2019-10-30 02:57 UTC

**Comment by yudawen** [comment] 2021-05-26 08:10
If the opt.num_stacks =1, it means the Hourglass-52 is adopted, right?
