### ISSUE TITLE
Visualization error while using ctdet_post_process function.

### ISSUE THREAD

**Issue by ljjyxz123** [xingyizhou/CenterNet#517] opened 2019-12-09 03:59 UTC
@xingyizhou 
Hello, XingYi,
I used ctdet_post_process to visualize the bboxes obtained from CenterNet, and really got some bboxes, but the bboxes seem to be not correct. Such as: 

![centernet_1_0](https://user-images.githubusercontent.com/2631417/70406169-cca63b80-1a7a-11ea-8211-899740248b9b.jpg)

my command to generate this result is:
python ./src/main.py ctdet --exp_id coco_dla --batch_size 16 --lr 5e-4 --gpus 4,5,6,7 --num_workers 16 --load_model ./models/ctdet_coco_dla_2x.pth --not_rand_crop

I used the pre-trained weights, and I thought the bboxes should be very precise after using the pre-trained weights.

Do you know why? Thank you very much!

**Comment by xingyizhou** [comment] 2019-12-09 17:06
You will need to use `demo.py` to evaluate on your own image. `post_process` converts the predicted bbox in the **original** image coordinate, while in your example it is resized and padded to 512x512.

**Comment by ljjyxz123** [comment] 2019-12-11 03:05
> You will need to use `demo.py` to evaluate on your own image. `post_process` converts the predicted bbox in the **original** image coordinate, while in your example it is resized and padded to 512x512.

@xingyizhou 
Thank you for your reply.

Can I post_process the coordinate to the resolution of 512x512? 
I read your code, and found that in the file ./src/lib/datasets/sample/ctdet.py, 
the dataset augmentation method transformed all of the images to be size of [512, 512, 3],
so I think post_process to the size of [512, 512, 3] will be very useful.

Could you give me some guidance on modifying the post_process() function to achieve my idea? Thank you very much!

**Comment by ljjyxz123** [comment] 2019-12-12 09:00
@xingyizhou 
Finally, I got it!

![centernet_orig_1_0](https://user-images.githubusercontent.com/2631417/70697558-b4dfe900-1d00-11ea-9df2-5c69257ab2eb.jpg)

I record the original size of the image, and resize the predicted bounding boxes to the resized image (512 * 512).

By the way, thank you very much for giving me the instructions!

**Comment by xingyizhou** [comment] 2019-12-12 21:59
Closing this now as the issue is resolved.

**Closed by xingyizhou** 2019-12-12 21:59 UTC
